
-- DRE estruturada por ano para empresa específica e grupo individual (Ex: BCO BRASIL S.A.)
SELECT
    CD_CONTA AS Conta,
    DS_CONTA AS Descricao,
    SUM(CASE WHEN ANO = 2025 THEN VL_CONTA ELSE 0 END) AS val_2025,  
    SUM(CASE WHEN ANO = 2024 THEN VL_CONTA ELSE 0 END) AS val_2024,
    SUM(CASE WHEN ANO = 2023 THEN VL_CONTA ELSE 0 END) AS val_2023,
    SUM(CASE WHEN ANO = 2022 THEN VL_CONTA ELSE 0 END) AS val_2022
FROM dre
WHERE
    DENOM_CIA = 'BCO BRASIL S.A.'
    AND VL_CONTA <> 0
    AND GRUPO_DFP LIKE '%INDIVIDUAL%'
GROUP BY
    CD_CONTA,
    DS_CONTA
ORDER BY
    CD_CONTA;
